[package]
name = "tmpl-cli"
version = "0.1.0"

description = "Template CLI"
license = "MIT"
repository = "https://github.com/ryanuo/tmpl-cli"
homepage = "https://ryanuo.cc"
authors = ["Ryanuo <ryanuo@aliyun.com>"]


[dependencies]
clap = "4.1"  # 处理命令行参数
git2 = "0.14"  # 与 Git 库交互
dialoguer = "0.9"
tempfile = "3"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"